---
- name: Setup Debug
  gather_facts: true
  hosts: kuroneko
  tasks:
    - name: docker-compose up
      shell: "NODE_NAME={{ inventory_hostname }} /snap/bin/docker-compose up -d"
      args:
        chdir: "{{ playbook_dir }}"
